spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/huf
    driverClassName: org.mariadb.jdbc.Driver
    username: likelion
    password: likelion11
  jpa:
    generate-ddl : true
    hibernate:
      ddl-auto: validate # db 컬럼과 일치하는지 확인
    properties:
      hibernate:
        format_sql: true # 로그 출력
  logging:
  level:
    org.hibernate.SQL: debug #로그 레벨 조정