#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    protocol: TLS
#    enabled-protocols: TLSv1.2
#    key-store: spring_key.p12
#    key-store-password :
#    ciphers: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHERSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384

spring:
  profiles:
    include: "local"
  datasource:
    url: ${spring.datasource.url}
    driverClassName: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    open-in-view: true
    generate-ddl : true
    hibernate:
      ddl-auto: update # db 컬럼과 일치하는지 확인
    properties:
      hibernate:
        format_sql: true # 로그 출력
        show_sql: true

  logging:
    config: classpath:log4j2.yml
  level:
    org.hibernate.SQL: debug #로그 레벨 조정

  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 30MB #multipart/form-data의 request 사이즈
      max-file-size: 10MB #총 파일 사이즈 제한
      location: C:\\upload


com:
  hallym:
    festival:
      upload:
        path: C:\\upload
