spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hallymfestival
    driverClassName: org.mariadb.jdbc.Driver
    username: likelion
    password: likelion11
  jpa:
    open-in-view: true
    generate-ddl : true
    hibernate:
      ddl-auto: create # db 컬럼과 일치하는지 확인
    properties:
      hibernate:
        format_sql: true # 로그 출력
        show_sql: true

  logging:
    config: classpath:log4j2.yml
  level:
    org.hibernate.SQL: debug #로그 레벨 조정

  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 30MB #multipart/form-data의 request 사이즈
      max-file-size: 10MB #총 파일 사이즈 제한
      location: C:\\upload


com:
  hallym:
    festival:
      upload:
        path: C:\\upload

