spring:
  profiles:
    include: "local"
  datasource:
    url: ${spring.datasource.url}
    driverClassName: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    open-in-view: true
    generate-ddl : true
    hibernate:
      ddl-auto: update # db 컬럼과 일치하는지 확인
    properties:
      hibernate:
        format_sql: true # 로그 출력
        show_sql: true

#Spring boot 2.6버전 이후에 spring.mvc.pathmatch.matching-strategy 값이 ant_apth_matcher에서 path_pattern_parser로 변경되면서 나타는 오류 해결
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  logging:
    config: classpath:log4j2.yml
  level:
    org.hibernate.SQL: debug #로그 레벨 조정

  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 30MB #multipart/form-data의 request 사이즈
      max-file-size: 10MB #총 파일 사이즈 제한
      location: C:\\upload


com:
  hallym:
    festival:
      upload:
        path: C:\\upload

